### ISSUE TITLE
很多源只能一个一个刷新

### ISSUE THREAD

**Issue by EX-Miracle** [zhanglun/lettura#10]
![Untitled](https://user-images.githubusercontent.com/70376567/200300296-d6394a43-473b-45ea-bab4-1b70f8673995.png)
在刷新的时候，所有的的源不能一次性全部刷新，必须点进去再刷新。
有的源也无法订阅，比如爱范儿 https://www.ifanr.com/feed

**Comment by zhanglun** [comment]
> ![Untitled](https://user-images.githubusercontent.com/70376567/200300296-d6394a43-473b-45ea-bab4-1b70f8673995.png) 在刷新的时候，所有的的源不能一次性全部刷新，必须点进去再刷新。 有的源也无法订阅，比如爱范儿 https://www.ifanr.com/feed

1. 这块的体验还在优化，具体完成时间目前未知。
2. ifanr的源数据暂时无法兼容，你可以试试这个地址 https://rsshub.app/ifanr/app。更多rss源可以在这里找到https://docs.rsshub.app/new-media.html#ai-fan-er-ifanr
