### ISSUE TITLE
features requests

### ISSUE THREAD

**Issue by katresars** [zhanglun/lettura#19]
Display icon description when hovering over it.
Youtube feed supported and parse videos from youtube links.

**Comment by zhanglun** [comment]
20366983f6bfde197f3b7a6dfc739fce05861a01

**Comment by zhanglun** [comment]
Now supports youtube channels! https://github.com/zhanglun/lettura/commit/a54a28dae7ccac8f2e6f00a46c99d0be31c1d3f2

you can find new release in https://github.com/zhanglun/lettura/releases/tag/v0.1.10
