### ISSUE TITLE
订阅了HelloGithub无法完整显示内容

### ISSUE THREAD

**Issue by csj5588** [zhanglun/lettura#22]
软件我很喜欢，首先表示支持
订阅了HelloGithub无法完整显示内容
订阅链接：https://hellogithub.com/rss

![image](https://github.com/zhanglun/lettura/assets/25579868/8f12faad-d959-492a-8417-95f37659d5d0)

**Comment by zhanglun** [comment]
订阅地址中没有返回完整网页内容，所以没有显示。后续有计划尝试实现抓取完整网页内容，但是暂时没有精力开发
