### ISSUE TITLE
macos arm (mac M) build

### ISSUE THREAD

**Issue by geneliu** [zhanglun/lettura#24]
**Is your feature request related to a problem? Please describe.**
There is macos x86 build, but not a build for the macos M (arm) delivery yet.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhanglun** [comment]
you can get artifacts in [here](https://github.com/zhanglun/lettura/releases). eg: https://github.com/zhanglun/lettura/releases/download/v0.1.12/Lettura_0.1.12_x64.dmg
