### ISSUE TITLE
Log file has expanded to 9GB

### ISSUE THREAD

**Issue by Chilfish** [zhanglun/lettura#31]
**Describe the bug**

你好，我很高兴使用这款轻便的 RSS 客户端。但我在使用了没多久过后，如图，我发现日志文件 `~\AppData\Roaming\com.lettura.dev\logs\Lettura.log` 的大小竟然达到了 9GB 的大小🤔

![image](https://github.com/zhanglun/lettura/assets/60336739/2e48b54a-f20b-4b60-ac66-5df0281a4dd9)

我不清楚这是否是 bug，下面两个附件分别是这个 log 的开头和结尾的部分。其中我发现里面包含了 rss 文章的内容，和像是 AST 的内容，我猜想这似乎导致了这个文件体积巨大的原因之一？

[lettura-head.log](https://github.com/zhanglun/lettura/files/13065741/lettura-head.log)
[lettura-tail.log](https://github.com/zhanglun/lettura/files/13065743/lettura-tail.log)

**To Reproduce**

我不知道该如何重现，仅是导入了 25 个来自 opml 的订阅，并同步，过一会就这样了。而且当我删除日志文件重复这个步骤的时候，并没能成功复现😥

**Expected behavior**

或许并不需要这么详细的日志？

**Desktop:**
 - OS: Windows10
 - Version 0.1.9-2_x64

**Comment by zhanglun** [comment]
感谢你的反馈。
产生这个问题的原因应该是我在开发阶段打印了太多内容，并且没有使用环境变量针对正式版本的日志进行优化。我会在后续的版本中优化这个问题。

**Comment by zhanglun** [comment]
[v0.1.9-3](https://github.com/zhanglun/lettura/releases/tag/v0.1.9-3) 中修改了日志输出的规则，大幅减少了日志的输出量，欢迎体验。
