### ISSUE TITLE
分组和全文加载功能

### ISSUE THREAD

**Issue by huhexian** [zhanglun/lettura#33]
分组功能是不是没有完善？没能找到将订阅源移动到指定分组的地方，希望能添加一键移动的功能。

另外，全文加载好像没有效果。

我使用的是 Windows 端最新版。

**Comment by huhexian** [comment]
![bug](https://github.com/zhanglun/lettura/assets/42113492/a65d4ce4-0075-4659-8713-e1b96f142d94)

还有一个Bug，或者说feature，点击文章的时候，folder会自动收起来。

**Comment by zhanglun** [comment]
全文加载还在一个实验性的功能，我暂时先下了。

**Comment by sunmking** [comment]
> 全文加载还是一个实验性的功能，我暂时先下了。

大胆上，我们帮你测

**Comment by zhanglun** [comment]
> > 全文加载还是一个实验性的功能，我暂时先下了。
> 
> 大胆上，我们帮你测

哈哈 感谢支持。实验阶段发现当时的版本并不是很好用，我暂时还没考虑好产品方案和技术实现。先打磨一下其他功能。
