### ISSUE TITLE
Fail to move feed into folders

### ISSUE THREAD

**Issue by BytesPirate** [zhanglun/lettura#37]
**Describe the bug**

I want to move my  feed into a folder.

**To Reproduce**

1. Move to My Subscriptions
2. Press and hold the left mouse button
3. Drag to folder

**Expected behavior**

Expect to move in successfully

**Desktop (please complete the following information):**

 - OS: [Win 11]
 - Version [v0.1.11]

**Additional context**

Maybe can add it to the context menu。

**Comment by zhanglun** [comment]
now you can drag feed into folder in [v0.1.12](https://github.com/zhanglun/lettura/releases/tag/v0.1.12) , and i will consider what you suggested about actions in context menu
