### ISSUE TITLE
RSS 只能订阅摘要部分，没有展示全部内容

### ISSUE THREAD

**Issue by buf1024** [zhanglun/lettura#39]
**Describe the bug**
RSS 只能订阅摘要部分，没有展示全部内容

**To Reproduce**
比如RSS订阅源：
https://feed.cnblogs.com/blog/u/177636/rss/
```
<id>https://www.cnblogs.com/coco1s/p/17881159.html</id>
<title type="text">【布局技巧】Flex 布局下居中溢出滚动截断问题 - ChokCoco</title>
<summary type="text">在页面布局中，我们经常会遇到/使用这么一类常见的布局，也就是列表内容水平居中于容器中，像是这样： &lt;ul class=&quot;g-contaner&quot;&gt; &lt;li&gt;&lt;/li&gt; &lt;li&gt;&lt;/li&gt; &lt;/ul&gt; ul { width: 500px; display: flex; flex-direction: r</summary>
<published>2023-12-07T02:29:00Z</published>
<updated>2023-12-07T02:29:00Z</updated>
```
或者
https://luoguochun.cn/index.xml
```
<item>
<title>rust 过程宏</title>
<link>https://luoguochun.cn/post/2023-12-26-rust-proc-macro/</link>
<pubDate>Tue, 26 Dec 2023 16:00:10 +0800</pubDate>
<guid>https://luoguochun.cn/post/2023-12-26-rust-proc-macro/</guid>
<description>简介 Rust 编程语言里面有两种宏系统，一种是声明宏（Declarative Macros），另一种为过程宏（Procedural Macros）。声明</description>
</item>
```
应该是能够读根据rss版本的不同取到其中的链接，展示链接里面的内容，不过好像实际上展示的是空白页。

**Screenshots**
![1](https://github.com/zhanglun/lettura/assets/634000/92d557e4-0f04-4978-9965-06262d775461)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 版本 120.0.6099.129（正式版本） (arm64)

**Additional context**
另外一个小建议哈，建议左侧两栏可以设置隐藏展开甚至是可以拖拽改变大小，比较占空间影响阅读。

**Comment by zhanglun** [comment]
我调整了顺序，优先展示解析到的description。
但是如果要展示全文，需要rss将全文内容输出到摘要对应的字段，也就是说需要源提供方的支持

**Comment by buf1024** [comment]
修改后，问题更多：

摘要部分点击后，再进来就没有了，不过详细部分并没有消失。

详情显示也显示不全。

<img width="1017" alt="image" src="https://github.com/zhanglun/lettura/assets/634000/34d8053b-1552-4c21-abcd-e3226edd0ac4">

**Comment by zhanglun** [comment]
<img width="845" alt="image" src="https://github.com/zhanglun/lettura/assets/3086358/d395bfd6-802d-4d09-a88b-9bf86279f8ec">

**Comment by buf1024** [comment]
好像并没有解决问题，详情还是没显示。而且各种各样的小问题非常多，等稳定些先，暂时不用先，感谢作者的贡献！！

<img width="1639" alt="image" src="https://github.com/zhanglun/lettura/assets/634000/570343f6-1acf-440d-9ffb-6150bfe3733c">
