### ISSUE TITLE
页面异常

### ISSUE THREAD

**Issue by houkunlin** [zhanglun/lettura#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/zhanglun/lettura/assets/12333292/690462ab-44e6-48cb-91eb-d8b3a364c8e0)
![image](https://github.com/zhanglun/lettura/assets/12333292/21851e73-4587-410a-a9d7-11629bc1471f)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser : chrome,edge
 - Version : latest

**Additional context**

**Comment by zhanglun** [comment]
same as #42
