### ISSUE TITLE
When installing the latest version on Windows 11, an error occurred when trying to access the settings.

### ISSUE THREAD

**Issue by Glyco-Protein** [zhanglun/lettura#47]
![屏幕截图 2024-04-17 000126](https://github.com/zhanglun/lettura/assets/156641373/e0f9c63e-987b-4441-9c64-2b12e7eff9e2)
![屏幕截图 2024-04-17 000149](https://github.com/zhanglun/lettura/assets/156641373/a35a985c-9470-494c-9bf9-187746424bc2)
![屏幕截图 2024-04-17 000155](https://github.com/zhanglun/lettura/assets/156641373/09a365cc-0216-424e-af05-c6e784dbe643)

**Comment by zhanglun** [comment]
A future version will fix this problem
