### ISSUE TITLE
Incorrect Max Width Calculations

### ISSUE THREAD

**Issue by neil-lobo** [zhanglun/lettura#48]
**Describe the bug**
Incorrect max width calculations result in "squished" containers.

**To Reproduce**
Steps to reproduce the behavior 1. :
1. Add any rss feed
2. view post

Steps to reproduce the behavior 2. :
1. Open settings
2. observe formatting issue

**Expected behavior**
Render properly 

**Screenshots**
Issue 1.
![image](https://github.com/zhanglun/lettura/assets/36115155/1cd23f3b-1c88-483d-b9e3-39b52e24fc5a)

Issue 2.
![image](https://github.com/zhanglun/lettura/assets/36115155/533e1012-3653-4bbf-a9d7-82294fbe0f5d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Native App
 - Version: v0.1.17

**Additional context**
Removing the `max-w` class seems to resolve the issue:
![image](https://github.com/zhanglun/lettura/assets/36115155/7bb4948d-a220-41f5-a24a-43460cb35a57)
![image](https://github.com/zhanglun/lettura/assets/36115155/1015d95e-065e-4d71-b889-3531be2de2b3)

Similarly, removing the `max-width` css property here fixes the other issue:
![image](https://github.com/zhanglun/lettura/assets/36115155/52a9e592-13b8-4ac3-8676-d4d8d874ac1e)
![image](https://github.com/zhanglun/lettura/assets/36115155/3117ad7e-d60e-4e3b-8574-8f3a35c909a4)

**Comment by neil-lobo** [comment]
just saw https://github.com/zhanglun/lettura/issues/42#issuecomment-2046958574, it seems to have fixed it, but new users will still face this issue on a fresh install

**Comment by zhanglun** [comment]
Please adjust it manually 🥹🥹🥹🥹 #42

**Comment by neil-lobo** [comment]
I think that this issue should be left open until the actual issue is solved. It would reduce the number of duplicate issues.
