### ISSUE TITLE
Hard to read/Unreadable Dark Mode Accent Colours

### ISSUE THREAD

**Issue by neil-lobo** [zhanglun/lettura#49]
**Describe the bug**
Some accent colours on dark mode make the titles unreadable, while others are very hard to read with

**To Reproduce**
1. Enable dark mode
2. set accent colour to black/blue
3. Observe unreadable title

OR

1. Enable dark mode
2. set accent colour to green/red
3. Observe hard to read title

**Expected behavior**
Use lighter versions of the accent colour for dark mode

**Screenshots**
![image](https://github.com/zhanglun/lettura/assets/36115155/1c6cad45-e01b-49fe-9d73-893db14e461d)
![image](https://github.com/zhanglun/lettura/assets/36115155/ddcda640-ec74-46e3-b597-676a67365804)
![image](https://github.com/zhanglun/lettura/assets/36115155/ce82dd1c-a365-40be-94bb-554b3a73e719)
![image](https://github.com/zhanglun/lettura/assets/36115155/8a81435c-23c1-4303-bfac-cd879dac9b47)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Native app
 - Version: v0.1.17

**Comment by zhanglun** [comment]
Yes, I didn’t do this well at the time. I am planning to reconstruct the ability of theme settings.

**Comment by zhanglun** [comment]
new version in https://github.com/zhanglun/lettura/releases/tag/v0.1.18
