### ISSUE TITLE
完善播客支持|Add More Support to Podcast

### ISSUE THREAD

**Issue by Jiang10086** [zhanglun/lettura#53]
**Is your feature request related to a problem? Please describe.**
软件非常漂亮优雅，现在软件确实能听播客，但没有音频控制界面，无法调节进度或调节倍速（这俩可以说是播客刚需）。而且也无法记住进度（每次点播放都会从头播）
This is an beautiful and elegant app, and can play podcast, but can't control play speed and go back or forward, also this app can't remember where this podcast is played.

**Describe the solution you'd like**
提供音频控制界面，可以调节进度和倍速，并且默认记住播放位置
Provides an audio control interface that can adjust progress and speed, and remembers the playback position by default

**Describe alternatives you've considered**
调用系统已经安装的播放器（比如mpv、PotPlayer）通过URI播放网络音频
Call the player installed on the system (such as mpv, PotPlayer) to play network audio through URI

**Additional context**

**Comment by zhanglun** [comment]
音频播放控制界面做了全面的修改和升级，现在支持播放，暂停，播放上一个/下一个等功能。
可以体验一下最新版本 [0.1.21](https://github.com/zhanglun/lettura/releases/tag/v0.1.21)

另外，倍速功能和调用外部播放器这两个功能暂时不考虑，未来也不一定会有支持的计划。
