### ISSUE TITLE
Folders cannot be deleted

### ISSUE THREAD

**Issue by holipay** [zhanglun/lettura#57]
If you delete a folder in the settings, or right-click to delete the folder, the software will crash.
在设置中删除文件夹，或者鼠标右键删除文件夹，软件闪退。

 os: windows 10
Lettura_0.1.17_x64_en-US

**Comment by holipay** [comment]
It may be that the Windows system disabling updates has affected the software's operation. Now when the software is opened, it immediately crashes.
可能是windows 系统禁用升级后影响到软件的运行。现在打开软件则直接闪退。

**Comment by zhanglun** [comment]
fixed in https://github.com/zhanglun/lettura/releases/tag/v0.1.18
