### ISSUE TITLE
no back botton

### ISSUE THREAD

**Issue by joeykini** [zhanglun/lettura#59]
点击feed内的链接之后跳转网页，但是无退出或者返回的按钮，只能退出软件重新打开
![WX20240615-235935@2x](https://github.com/zhanglun/lettura/assets/73977767/7cb4178e-6309-4b2a-b83d-aa42d1455b70)
![WX20240615-235857@2x](https://github.com/zhanglun/lettura/assets/73977767/e350fad3-b08b-4b35-8e00-588d6edb4d09)

**Comment by zhanglun** [comment]
麻烦在issue中提供一下对应的源地址和文章链接

**Comment by joeykini** [comment]
抱歉抱歉，刚刚试了下，直接跳转了浏览器的网页，昨天这个情况不知道为啥了....
大佬后续可以添加翻译的功能吗，双语对照学习英文

**Comment by joeykini** [comment]
抱歉抱歉，昨天不知道啥情况没有跳转到浏览器网页，刚刚试了下是正常跳转到网页的....

zhanglun ***@***.***> 于2024年6月16日周日 13:25写道：

**Comment by zhanglun** [comment]
> 抱歉抱歉，刚刚试了下，直接跳转了浏览器的网页，昨天这个情况不知道为啥了.... 大佬后续可以添加翻译的功能吗，双语对照学习英文

我明白你说的这个能力，但是对于具体的需求细节和诉求，你会比我更加清楚。所以我建议你提一个功能性的issue，详细说说你想要的需求能力，以帮助我更好地去设计实现方案。
