### ISSUE TITLE
Hi, I am learning your code, is it a better choice to place db into frontend?

### ISSUE THREAD

**Issue by rwecho** [zhanglun/lettura#9]
Your job is great, I am learning the rust language through this project.
In the browser, there is an IndexedDB we can use. Relative to the rust sqlite,  It integrates better with react.
thanks.

**Comment by zhanglun** [comment]
This is a Rust project, I would like to migration database to SQLite writen with Rust. you can access the version with indexedDB from the branch named [indexedDB](https://github.com/zhanglun/lettura/tree/indexedDB),
